---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
    tier: db
spec:
  containers:
  - name: rabbitmq
    imagePullPolicy: Always
    image: rabbitmq
    ports:
      - containerPort: 5672 # For Message queue
      - containerPort: 15672 # To open RabbitMQ in HTTP browser
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    name: rabbitmq
    tier: db
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: http
  type: ClusterIP
---