---
apiVersion: v1
kind: Pod
metadata: 
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - name: catalogue
    imagePullPolicy: Always
    image: rmahesh9/catalogue:k8
    resources: 
      requests: 
        cpu: "100m"
        memory: "128Mi"
      limits: 
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080  # container port